# Site Settings
lang: en
title: PetrVey
tagline: Personal Website
email: vohnickypetr@gmail.com
description: Personal Website 
permalink: pretty

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

paginate: 5
paginate_path: "/blog/page:num"

livereload: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

plugins:
   - jekyll-leaflet
   
collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

